version: '2'

services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=linux
      - POSTGRES_DB=postgres
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh

  n8n:
    image: n8n_bluetti:v0.1
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=root
      - N8N_BASIC_AUTH_PASSWORD=linux
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - /data/n8n:/home/node/.n8n
    command: /bin/sh -c "n8n start --tunnel"
    depends_on:
      - postgres

networks:
  default:
    external:
      name: "n8n_bridge"